/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ingsoftware.prestamosbiblioteca;

import com.ingsoftware.interfaces.DAObibliotecarios;
import com.ingsoftware.interfaces.DAOclientes;
import com.ingsoftware.models.clientes;
import javax.swing.JOptionPane;

/**
 *
 * @author Adrian Quej
 */
public class nuevoUsuario extends javax.swing.JPanel {

    /**
     * Creates new form nuevoUsuario
     */
    boolean isEdition = false;
    clientes clienteEdit;
    
    public nuevoUsuario() {
        initComponents();
        isEdition=false;
        initStyles();
    }

    public nuevoUsuario(clientes cli){
        initComponents();
        clienteEdit= cli;
        isEdition = true;
        initStyles();
    }
    
    public void  initStyles(){
        if (isEdition) {
            Title.setText("EDITAR UN USUARIO");
            jButton1.setText("EDITAR");
            if (clienteEdit != null) {
                elnombre.setText(clienteEdit.getNombre());
                eldomicilio.setText(clienteEdit.getDireccion());
                eltelefono.setText(clienteEdit.getTelefono());
                
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Text1 = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        elnombre = new javax.swing.JTextField();
        eldomicilio = new javax.swing.JTextField();
        Text2 = new javax.swing.JLabel();
        eltelefono = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 27, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Text1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Text1.setForeground(new java.awt.Color(255, 255, 255));
        Text1.setText("Teléfono");
        jPanel1.add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Registrar nuevo Usuario");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Text3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Text3.setForeground(new java.awt.Color(255, 255, 255));
        Text3.setText("Nombre");
        jPanel1.add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        elnombre.setForeground(new java.awt.Color(102, 102, 102));
        elnombre.setText("Ingrese el nombre");
        elnombre.setBorder(null);
        elnombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elnombreMousePressed(evt);
            }
        });
        elnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elnombreActionPerformed(evt);
            }
        });
        jPanel1.add(elnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 260, 30));

        eldomicilio.setForeground(new java.awt.Color(102, 102, 102));
        eldomicilio.setText("Ingrese el domicilio");
        eldomicilio.setBorder(null);
        eldomicilio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eldomicilioMousePressed(evt);
            }
        });
        eldomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eldomicilioActionPerformed(evt);
            }
        });
        jPanel1.add(eldomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 260, 30));

        Text2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Text2.setForeground(new java.awt.Color(255, 255, 255));
        Text2.setText("Domicilio");
        jPanel1.add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        eltelefono.setForeground(new java.awt.Color(102, 102, 102));
        eltelefono.setText("Ingrese un número telefónico");
        eltelefono.setBorder(null);
        eltelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eltelefonoMousePressed(evt);
            }
        });
        eltelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eltelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(eltelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 260, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/account-multiple.png"))); // NOI18N
        jButton1.setText("REGISTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 120, 47));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 430, 300));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/COMPU.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void eltelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eltelefonoMousePressed
        eltelefono.setText("");
    }//GEN-LAST:event_eltelefonoMousePressed

    private void eltelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eltelefonoActionPerformed
        jButton1.doClick();
    }//GEN-LAST:event_eltelefonoActionPerformed

    private void eldomicilioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eldomicilioMousePressed
        eldomicilio.setText("");
    }//GEN-LAST:event_eldomicilioMousePressed

    private void eldomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eldomicilioActionPerformed
        jButton1.doClick();
    }//GEN-LAST:event_eldomicilioActionPerformed

    private void elnombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elnombreMousePressed
        elnombre.setText("");
    }//GEN-LAST:event_elnombreMousePressed

    private void elnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elnombreActionPerformed
        jButton1.doClick();
    }//GEN-LAST:event_elnombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre = elnombre.getText();
        String telefono = eltelefono.getText();
        String domicilio = eldomicilio.getText();
        
        //VALIDACIONES    
        if(elnombre.getText().equals("Ingrese el nombre") || eltelefono.getText().equals("Ingrese un número telefónico")
            || eldomicilio.getText().equals("Ingrese el domicilio") ){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            elnombre.requestFocus();
            return;
        }
        
        
        com.ingsoftware.models.clientes cli = isEdition ?  clienteEdit: new com.ingsoftware.models.clientes();
        cli.setNombre(nombre);
        cli.setTelefono(telefono);
        cli.setDireccion(domicilio);
        
        try {
            DAOclientes dao = new DAOclientesImpl();
            if(!isEdition){
            dao.registrar(cli);
            } else {
            dao.modificar(cli);
            }
            
            String sepudo = isEdition ? "modificado" : "registrado";
            
            JOptionPane.showMessageDialog(null, "Cliente " +sepudo+ " con exito");
            
            if(!isEdition){
            elnombre.setText("");
            eltelefono.setText("");
            eldomicilio.setText("");
            }
        } catch (Exception e){
             String nosepudo = isEdition ? "modificar" : "registrar";
            JOptionPane.showMessageDialog(null, "Hubo un error al "+ nosepudo+ " el cliente");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel body;
    private javax.swing.JTextField eldomicilio;
    private javax.swing.JTextField elnombre;
    private javax.swing.JTextField eltelefono;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
