/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ingsoftware.prestamosbiblioteca;

import com.ingsoftware.interfaces.DAObibliotecarios;
import com.ingsoftware.interfaces.DAOprestamo;
import com.ingsoftware.models.bibliotecarios;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Adrian Quej
 */
public class nuevoPrestamo extends javax.swing.JPanel {

    /**
     * Creates new form nuevoPrestamo
     */
    public nuevoPrestamo() {
        initComponents();
    }
    
    public nuevoPrestamo(String bibliotecario){
        initComponents();
        jt_foliobibliotecario.setText(bibliotecario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        lb_foliolibro = new javax.swing.JLabel();
        jt_foliolibro = new javax.swing.JTextField();
        lb_foliousuario = new javax.swing.JLabel();
        jt_foliousuario = new javax.swing.JTextField();
        lb_foliobibliotecario = new javax.swing.JLabel();
        jt_foliobibliotecario = new javax.swing.JTextField();
        lb_fechaprestamo = new javax.swing.JLabel();
        jt_fechaprestamo = new javax.swing.JTextField();
        lb_fechadevolucion = new javax.swing.JLabel();
        jt_fechadevolucion = new javax.swing.JTextField();
        jTB_tipoprestamo = new javax.swing.JToggleButton();
        txt_tipoPrestamo = new javax.swing.JLabel();
        btn_nuevoprestamo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setMinimumSize(new java.awt.Dimension(750, 430));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setToolTipText("");
        jPanel1.setMinimumSize(new java.awt.Dimension(750, 430));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("NUEVO PRESTAMO");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 340, -1));

        lb_foliolibro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_foliolibro.setText("FOLIO LIBRO:");
        jPanel1.add(lb_foliolibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 340, -1));

        jt_foliolibro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jt_foliolibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 340, -1));

        lb_foliousuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_foliousuario.setText("FOLIO USUARIO:");
        jPanel1.add(lb_foliousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 340, 32));

        jt_foliousuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jt_foliousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 340, -1));

        lb_foliobibliotecario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_foliobibliotecario.setText("NOMBRE BIBLIOTECARIO:");
        jPanel1.add(lb_foliobibliotecario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 340, 32));

        jt_foliobibliotecario.setEditable(false);
        jt_foliobibliotecario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jt_foliobibliotecario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 340, -1));

        lb_fechaprestamo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_fechaprestamo.setText("FECHA PRESTAMO:");
        jPanel1.add(lb_fechaprestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 340, 32));

        jt_fechaprestamo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jt_fechaprestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 340, -1));

        lb_fechadevolucion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_fechadevolucion.setText("FECHA DEVOLUCION");
        jPanel1.add(lb_fechadevolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 340, 32));

        jt_fechadevolucion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jt_fechadevolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 340, -1));

        jTB_tipoprestamo.setText("EN BIBLIOTECA");
        jTB_tipoprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTB_tipoprestamoActionPerformed(evt);
            }
        });
        jPanel1.add(jTB_tipoprestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 131, 40));

        txt_tipoPrestamo.setText("TIPO PRESTAMO:");
        jPanel1.add(txt_tipoPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 105, 40));

        btn_nuevoprestamo.setText("Añadir Prestamo");
        btn_nuevoprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoprestamoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_nuevoprestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bibliotecaPrestamo_2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 220, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTB_tipoprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTB_tipoprestamoActionPerformed
        if (jTB_tipoprestamo.isSelected()) {
            jTB_tipoprestamo.setText("DOMICILIO");
        } else {
            jTB_tipoprestamo.setText("EN BIBLIOTECA");
        }
    }//GEN-LAST:event_jTB_tipoprestamoActionPerformed

    private void btn_nuevoprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoprestamoActionPerformed
        bibliotecarios bib = new bibliotecarios();
        DAObibliotecarios pres = new DAObibliotecariosImpl();
        try {
            bib = pres.buscarBibliotecario(jt_foliobibliotecario.getText());
            
        } catch (Exception ex) {
            Logger.getLogger(nuevoPrestamo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        int libroid = Integer.parseInt(jt_foliolibro.getText());
        int bibliotecarioid = bib.getBibliotecarioID();
        int clienteid = Integer.parseInt(jt_foliousuario.getText());
        String fechaprestamo = jt_fechaprestamo.getText();
        String fechadevolucion = jt_fechadevolucion.getText();
        
        String tipoprestamo ="";
        
        if(jTB_tipoprestamo.isSelected()){
            tipoprestamo = "DOMICILIO";
        } else {
            tipoprestamo = "EN BIBLIOTECA";
        }
        
        com.ingsoftware.models.prestamo pre = new com.ingsoftware.models.prestamo();
        pre.setLibroID(libroid);
        pre.setBibliotecarioID(bibliotecarioid);
        pre.setClienteID(clienteid);
        pre.setFecha_prestamo(fechaprestamo);
        pre.setFecha_devolucion(fechadevolucion);
        pre.setTipo_prestamo(tipoprestamo);
        
        try {
            DAOprestamo dao = new DAOprestamoImpl();
            dao.registrar(pre);
            JOptionPane.showMessageDialog(null, "Prestamo agregado con exito");
            jt_foliolibro.setText("");
            jt_foliousuario.setText("");
            jt_fechaprestamo.setText("");
            jt_fechadevolucion.setText("");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Hubo un error al añadir el prestamo");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_nuevoprestamoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_nuevoprestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jTB_tipoprestamo;
    private javax.swing.JTextField jt_fechadevolucion;
    private javax.swing.JTextField jt_fechaprestamo;
    private javax.swing.JTextField jt_foliobibliotecario;
    private javax.swing.JTextField jt_foliolibro;
    private javax.swing.JTextField jt_foliousuario;
    private javax.swing.JLabel lb_fechadevolucion;
    private javax.swing.JLabel lb_fechaprestamo;
    private javax.swing.JLabel lb_foliobibliotecario;
    private javax.swing.JLabel lb_foliolibro;
    private javax.swing.JLabel lb_foliousuario;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel txt_tipoPrestamo;
    // End of variables declaration//GEN-END:variables
}
