/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ingsoftware.prestamosbiblioteca;

import com.ingsoftware.interfaces.DAOclientes;
import com.ingsoftware.interfaces.DAOlibros;
import com.ingsoftware.models.libros;
import javax.swing.JOptionPane;

/**
 *
 * @author Adrian Quej
 */
public class nuevoLibro extends javax.swing.JPanel {

    /**
     * Creates new form nuevoLibro
     */
    boolean isEdition = false;
    libros libroEdit;
    public nuevoLibro() {
        initComponents();
        isEdition=false;
        initStyles();
    }
    
     public nuevoLibro(libros lib){
        initComponents();
        libroEdit= lib;
        isEdition = true;
        initStyles();
    }
    
     public void  initStyles(){
        if (isEdition) {
            Title.setText("EDITAR UN LIBRO");
            jButton1.setText("EDITAR");
            if (libroEdit != null) {
                elnombre.setText(libroEdit.getNombre_libro());
                elautor.setText(libroEdit.getAutor());
                elISBN.setText(libroEdit.getISBN());
                elano.setText(""+libroEdit.getAno());
                elnumcopia.setText(""+libroEdit.getNum_copia());                
            }
        }
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        Text6 = new javax.swing.JLabel();
        elnombre = new javax.swing.JTextField();
        Text7 = new javax.swing.JLabel();
        elano = new javax.swing.JTextField();
        Text8 = new javax.swing.JLabel();
        elautor = new javax.swing.JTextField();
        Text9 = new javax.swing.JLabel();
        elISBN = new javax.swing.JTextField();
        elnumcopia = new javax.swing.JTextField();
        Text10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Registrar nuevo Libro");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, 20));

        Text6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Text6.setForeground(new java.awt.Color(255, 255, 255));
        Text6.setText("Nombre");
        add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        elnombre.setForeground(new java.awt.Color(102, 102, 102));
        elnombre.setText("Ingrese el Título");
        elnombre.setBorder(null);
        elnombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elnombreMousePressed(evt);
            }
        });
        elnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elnombreActionPerformed(evt);
            }
        });
        add(elnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 260, 30));

        Text7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Text7.setForeground(new java.awt.Color(255, 255, 255));
        Text7.setText("Año");
        add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        elano.setForeground(new java.awt.Color(102, 102, 102));
        elano.setText("Ingrese el año de Publicación");
        elano.setBorder(null);
        elano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elanoMousePressed(evt);
            }
        });
        elano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elanoActionPerformed(evt);
            }
        });
        add(elano, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 260, 30));

        Text8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Text8.setForeground(new java.awt.Color(255, 255, 255));
        Text8.setText("Autor");
        add(Text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        elautor.setForeground(new java.awt.Color(102, 102, 102));
        elautor.setText("Ingrese el nombre del Autor/es");
        elautor.setBorder(null);
        elautor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elautorMousePressed(evt);
            }
        });
        elautor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elautorActionPerformed(evt);
            }
        });
        add(elautor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 260, 30));

        Text9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Text9.setForeground(new java.awt.Color(255, 255, 255));
        Text9.setText("ISBN");
        add(Text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        elISBN.setForeground(new java.awt.Color(102, 102, 102));
        elISBN.setText("Ingrese el ISBN");
        elISBN.setBorder(null);
        elISBN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elISBNMousePressed(evt);
            }
        });
        elISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elISBNActionPerformed(evt);
            }
        });
        add(elISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 260, 30));

        elnumcopia.setForeground(new java.awt.Color(102, 102, 102));
        elnumcopia.setText("Numero Copia Biblioteca");
        elnumcopia.setBorder(null);
        elnumcopia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elnumcopiaMousePressed(evt);
            }
        });
        elnumcopia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elnumcopiaActionPerformed(evt);
            }
        });
        add(elnumcopia, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 150, 30));

        Text10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Text10.setForeground(new java.awt.Color(255, 255, 255));
        Text10.setText("Numero Copia");
        add(Text10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book-open-page-variant.png"))); // NOI18N
        jButton1.setText("REGISTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 130, 71));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 430, 300));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/COMPU.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void elnombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elnombreMousePressed
        elnombre.setText("");
    }//GEN-LAST:event_elnombreMousePressed

    private void elnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elnombreActionPerformed
        jButton1.doClick();
    }//GEN-LAST:event_elnombreActionPerformed

    private void elanoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elanoMousePressed
        elano.setText("");
    }//GEN-LAST:event_elanoMousePressed

    private void elanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elanoActionPerformed
        jButton1.doClick();
    }//GEN-LAST:event_elanoActionPerformed

    private void elautorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elautorMousePressed
        elautor.setText("");
    }//GEN-LAST:event_elautorMousePressed

    private void elautorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elautorActionPerformed
        jButton1.doClick();
    }//GEN-LAST:event_elautorActionPerformed

    private void elISBNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elISBNMousePressed
        elISBN.setText("");
    }//GEN-LAST:event_elISBNMousePressed

    private void elISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elISBNActionPerformed
        jButton1.doClick();
    }//GEN-LAST:event_elISBNActionPerformed

    private void elnumcopiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elnumcopiaMousePressed
        elnumcopia.setText("");
    }//GEN-LAST:event_elnumcopiaMousePressed

    private void elnumcopiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elnumcopiaActionPerformed
        jButton1.doClick();
    }//GEN-LAST:event_elnumcopiaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre = elnombre.getText();
        String autor = elautor.getText();
        String isbn = elISBN.getText();
        int ano = Integer.parseInt(elano.getText());
        int copia = Integer.parseInt(elnumcopia.getText());
        
        //VALIDACIONES    
        if(elnombre.getText().equals("Ingrese el Título del libro") || elautor.getText().equals("Ingrese el nombre del Autor/es")
            || elISBN.getText().equals("Ingrese el ISBN del libro") ){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            elnombre.requestFocus();
            return;
        }
        
        
        com.ingsoftware.models.libros lib = isEdition ?  libroEdit: new com.ingsoftware.models.libros();
        lib.setNombre_libro(nombre);
        lib.setAutor(autor);
        lib.setISBN(isbn);
        lib.setAno(ano);
        lib.setNum_copia(copia);
        
        try {
            DAOlibros dao = new DAOlibrosImpl();
            if(!isEdition){
            dao.registrar(lib);
            } else {
            dao.modificar(lib);
            }
            
            String sepudo = isEdition ? "modificado" : "registrado";
            
            JOptionPane.showMessageDialog(null, "Libro " +sepudo+ " con exito");
            
            if(!isEdition){
            elnombre.setText("");
            elautor.setText("");
            elISBN.setText("");
            elano.setText("");
            elnumcopia.setText("");
            }
        } catch (Exception e){
             String nosepudo = isEdition ? "modificar" : "registrar";
            JOptionPane.showMessageDialog(null, "Hubo un error al "+ nosepudo+ " el libro");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text10;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text8;
    private javax.swing.JLabel Text9;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField elISBN;
    private javax.swing.JTextField elano;
    private javax.swing.JTextField elautor;
    private javax.swing.JTextField elnombre;
    private javax.swing.JTextField elnumcopia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
