/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ingsoftware.prestamosbiblioteca;

import com.ingsoftware.interfaces.DAOclientes;
import com.ingsoftware.interfaces.DAOlibros;
import com.ingsoftware.models.libros;
import javax.swing.JOptionPane;

/**
 *
 * @author Adrian Quej
 */
public class nuevoLibro extends javax.swing.JPanel {

    /**
     * Creates new form nuevoLibro
     */
    boolean isEdition = false;
    libros libroEdit;
    public nuevoLibro() {
        initComponents();
        isEdition=false;
        initStyles();
    }
    
     public nuevoLibro(libros lib){
        initComponents();
        libroEdit= lib;
        isEdition = true;
        initStyles();
    }
    
     public void  initStyles(){
        if (isEdition) {
            Title.setText("EDITAR UN LIBRO");
            jButton1.setText("EDITAR");
            if (libroEdit != null) {
                elnombre.setText(libroEdit.getNombre_libro());
                elautor.setText(libroEdit.getAutor());
                elISBN.setText(libroEdit.getISBN());
                elano.setText(""+libroEdit.getAno());
                elnumcopia.setText(""+libroEdit.getNum_copia());                
            }
        }
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Text6 = new javax.swing.JLabel();
        elnombre = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Text7 = new javax.swing.JLabel();
        elano = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        Text8 = new javax.swing.JLabel();
        elautor = new javax.swing.JTextField();
        Text9 = new javax.swing.JLabel();
        elISBN = new javax.swing.JTextField();
        elnumcopia = new javax.swing.JTextField();
        Text10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Registrar nuevo Libro");

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));

        Text6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text6.setText("Nombre");

        elnombre.setForeground(new java.awt.Color(102, 102, 102));
        elnombre.setText("Ingrese el Título");
        elnombre.setBorder(null);
        elnombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elnombreMousePressed(evt);
            }
        });
        elnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elnombreActionPerformed(evt);
            }
        });

        jSeparator7.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator7.setPreferredSize(new java.awt.Dimension(200, 10));

        Text7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text7.setText("Año");

        elano.setForeground(new java.awt.Color(102, 102, 102));
        elano.setText("Ingrese la Fecha de Publicación");
        elano.setBorder(null);
        elano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elanoMousePressed(evt);
            }
        });
        elano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elanoActionPerformed(evt);
            }
        });

        jSeparator8.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator8.setPreferredSize(new java.awt.Dimension(200, 10));

        Text8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text8.setText("Autor");

        elautor.setForeground(new java.awt.Color(102, 102, 102));
        elautor.setText("Ingrese el nombre del Autor/es");
        elautor.setBorder(null);
        elautor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elautorMousePressed(evt);
            }
        });
        elautor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elautorActionPerformed(evt);
            }
        });

        Text9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text9.setText("ISBN");

        elISBN.setForeground(new java.awt.Color(102, 102, 102));
        elISBN.setText("Ingrese la Categoría del Libro");
        elISBN.setBorder(null);
        elISBN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elISBNMousePressed(evt);
            }
        });
        elISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elISBNActionPerformed(evt);
            }
        });

        elnumcopia.setForeground(new java.awt.Color(102, 102, 102));
        elnumcopia.setText("Ingrese la edición");
        elnumcopia.setBorder(null);
        elnumcopia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elnumcopiaMousePressed(evt);
            }
        });
        elnumcopia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elnumcopiaActionPerformed(evt);
            }
        });

        Text10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text10.setText("Numero Copia");

        jButton1.setText("REGISTRAR LIBRO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Text6)
                    .addComponent(elnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text7)
                    .addComponent(elano, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Text8)
                    .addComponent(elautor, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text9)
                    .addComponent(elISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text10)
                    .addComponent(elnumcopia, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
            .addGroup(layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(Title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(80, 80, 80)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 502, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Text8)
                        .addGap(0, 0, 0)
                        .addComponent(elautor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(Text9)
                        .addGap(0, 0, 0)
                        .addComponent(elISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(Text10)
                        .addGap(0, 0, 0)
                        .addComponent(elnumcopia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(Text6)
                        .addGap(0, 0, 0)
                        .addComponent(elnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(Text7)
                        .addGap(0, 0, 0)
                        .addComponent(elano, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 1, Short.MAX_VALUE)
                    .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(150, 150, 150)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 54, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void elnombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elnombreMousePressed
        elnombre.setText("");
    }//GEN-LAST:event_elnombreMousePressed

    private void elnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elnombreActionPerformed
        jButton1.doClick();
    }//GEN-LAST:event_elnombreActionPerformed

    private void elanoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elanoMousePressed
        elano.setText("");
    }//GEN-LAST:event_elanoMousePressed

    private void elanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elanoActionPerformed
        jButton1.doClick();
    }//GEN-LAST:event_elanoActionPerformed

    private void elautorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elautorMousePressed
        elautor.setText("");
    }//GEN-LAST:event_elautorMousePressed

    private void elautorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elautorActionPerformed
        jButton1.doClick();
    }//GEN-LAST:event_elautorActionPerformed

    private void elISBNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elISBNMousePressed
        elISBN.setText("");
    }//GEN-LAST:event_elISBNMousePressed

    private void elISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elISBNActionPerformed
        jButton1.doClick();
    }//GEN-LAST:event_elISBNActionPerformed

    private void elnumcopiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elnumcopiaMousePressed
        elnumcopia.setText("");
    }//GEN-LAST:event_elnumcopiaMousePressed

    private void elnumcopiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elnumcopiaActionPerformed
        jButton1.doClick();
    }//GEN-LAST:event_elnumcopiaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre = elnombre.getText();
        String autor = elautor.getText();
        String isbn = elISBN.getText();
        int ano = Integer.parseInt(elano.getText());
        int copia = Integer.parseInt(elnumcopia.getText());
        
        //VALIDACIONES    
        if(elnombre.getText().equals("Ingrese el Título del libro") || elautor.getText().equals("Ingrese el nombre del Autor/es")
            || elISBN.getText().equals("Ingrese el ISBN del libro") ){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            elnombre.requestFocus();
            return;
        }
        
        
        com.ingsoftware.models.libros lib = isEdition ?  libroEdit: new com.ingsoftware.models.libros();
        lib.setNombre_libro(nombre);
        lib.setAutor(autor);
        lib.setISBN(isbn);
        lib.setAno(ano);
        lib.setNum_copia(copia);
        
        try {
            DAOlibros dao = new DAOlibrosImpl();
            if(!isEdition){
            dao.registrar(lib);
            } else {
            dao.modificar(lib);
            }
            
            String sepudo = isEdition ? "modificado" : "registrado";
            
            JOptionPane.showMessageDialog(null, "Libro " +sepudo+ " con exito");
            
            if(!isEdition){
            elnombre.setText("");
            elautor.setText("");
            elISBN.setText("");
            elano.setText("");
            elnumcopia.setText("");
            }
        } catch (Exception e){
             String nosepudo = isEdition ? "modificar" : "registrar";
            JOptionPane.showMessageDialog(null, "Hubo un error al "+ nosepudo+ " el libro");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text10;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text8;
    private javax.swing.JLabel Text9;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel body;
    private javax.swing.JTextField elISBN;
    private javax.swing.JTextField elano;
    private javax.swing.JTextField elautor;
    private javax.swing.JTextField elnombre;
    private javax.swing.JTextField elnumcopia;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    // End of variables declaration//GEN-END:variables
}
